REFACTOR: renamed Textbox into TextInput
nl-design-system/rijkshuisstijl-community pull request #1034
Opened 2024-12-23 14:43 UTC by JoeriRoijenga

2024-12-23 15:53 UTC, Rerbun requested changes
Het is niet de bedoeling dat we die hernoemen naar textbox, text input is de juiste naam, Utrecht gaat dit ook aanpassen. We zouden dit ook zelf bij Utrecht kunnen aanpassen maar dat is een breaking change, dus dat is wel risky. Het component van NL Design System heeft al de juiste naam; TextInput: https://www.nldesignsystem.nl/text-input
DIt was ook de reden dat we bij het oppakken van het component hebben gekozen voor de naam TextInput

Edit: ik las blijkbaar van rechts naar links. Resolved.

2024-12-24 07:44 UTC, Rerbun submitted a review, later dismissed

2024-12-24 08:27 UTC, Rerbun commented on packages/components-react/src/TextInput.test.tsx
> +describe('Textbox', () => {
Hier nog een laatste textbox

2024-12-24 08:28 UTC, Rerbun commented on packages/storybook/src/community/text-input.stories.tsx
> +          return code.replace(/Textbox/g, 'TextInput');
Waar is dit voor?

2024-12-24 08:31 UTC, JoeriRoijenga commented on packages/storybook/src/community/text-input.stories.tsx
> +          return code.replace(/Textbox/g, 'TextInput');
Dit is nodig om `<Textbox>` in the example als `<TextInput>` te tonen...
![Screenshot 2024-12-24 at 09 30 20](https://github.com/user-attachments/assets/900345f2-ef8b-4a3e-8351-9f9a7474686e)

Ik zag niet echt een andere manier, dit gaat dus wel goed bij `FormFieldTextInput`, mijn vermoeden is dat het komt omdat wij die een `DisplayName` meegeven: https://github.com/nl-design-system/rijkshuisstijl-community/blob/610563dd005f623987a94340d4b8ac651fd570e9/packages/components-react/src/FormFieldTextInput.tsx#L50

Als je ideeën hebt, laat maar weten

2024-12-24 08:31 UTC, JoeriRoijenga commented on packages/components-react/src/TextInput.test.tsx
> +describe('Textbox', () => {
Aangepast

2024-12-24 09:10 UTC, merged