Feature/alert
nl-design-system/rijkshuisstijl-community pull request #517
Opened 2024-08-06 14:09 UTC by AdhamAH

Ik heb deze #511 PR gebruikt voor de token

@Robbert Ik weet niet als deze manier is goed. Maar ik heb de logic voor kleuren en iconen weg uit storybook gehaald en bij de `components-react` package gezetten 

![Screenshot from 2024-08-06 14-27-30](https://github.com/user-attachments/assets/4a8213ef-8b15-4baa-b7a8-c03786ab7c6b)

2024-08-16 08:49 UTC, MeesD94 commented on .github/workflows/continuous-deployment.yml
Hoezo is dit bestand aangepast?

2024-08-16 08:55 UTC, AdhamAH commented on .github/workflows/continuous-deployment.yml
Als je je herinnert, de test en lint faalden. De reden was dat er geen build is van de iconen uit de` @rijkshuisstijl-community/web-components-react`. Daarom ik een stap gezetten om de package bouwen

2024-08-16 08:57 UTC, MeesD94 commented on packages/storybook/src/community/alert.stories.tsx
De color van de tekst komt niet overeen met hoe die staan in de Figma bibliotheek. Ook zie ik [hier](https://rijkshuisstijl-community-git-feature-alert-nl-design-system.vercel.app/?path=/docs/rijkshuisstijl-alert--docs) de icons niet.

Kijk even in [hier](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1179-3892&t=LIOB24f5i57Z2t20-0) om te controleren of de styling hieraan voldoet.

2024-08-16 08:58 UTC, MeesD94 requested changes
De Styling clomp niet helemaal overeen met wat op [Figma](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=1179-3892&t=LIOB24f5i57Z2t20-0) staat.

2024-08-16 09:00 UTC, MeesD94 commented on .github/workflows/continuous-deployment.yml
Misschien is het dan beter om het in een aparte issue te fixen?

2024-08-16 09:11 UTC, Rerbun requested changes

2024-08-16 09:11 UTC, Rerbun commented on packages/components-react/package.json
> +    "@rijkshuisstijl-community/web-components-react": "workspace:*"
Niet alfabetisch

2024-08-16 09:11 UTC, Rerbun commented on packages/storybook/src/community/alert.stories.tsx
Er is iets geks aan de hand met de icons waarbij ze lokaal wel te zien zijn maar in de storybook deployment in vercel niet :(

2024-08-16 09:11 UTC, Rerbun commented on packages/components-react/src/Alert.tsx
> +import { Heading, Icon, Paragraph, Alert as UAlert } from '@utrecht/component-library-react/dist/css-module';
Deze styling gebruikt op sommige plekken niet de goede tokens (tekstkleur is bijvoorbeeld utrecht-document-color terwijl dit in het design blauw is). Je kan het beste losse styling toevoegen zoals Mees en ik dat ook hebben gedaan met de accordion en de unordered list (#528 en #496)

2024-08-16 10:28 UTC, AdhamAH commented on .github/workflows/continuous-deployment.yml
Done! #543

2024-08-16 10:59 UTC, AdhamAH commented on packages/components-react/src/Alert.tsx
> +import { Heading, Icon, Paragraph, Alert as UAlert } from '@utrecht/component-library-react/dist/css-module';
Als ik @MeesD94 verteld, de heading style komt uit de `Heading` component. Wanner ik heb de push gedaan de heading PR was niet merged . De paragraph style ook komt uit de Paragraph` component

2024-08-16 11:10 UTC, Rerbun commented on packages/components-react/package.json
> +    "@rijkshuisstijl-community/web-components-react": "workspace:*"
Bijna goed, nog 1 omhoog :D

2024-08-16 11:16 UTC, Rerbun commented on packages/components-react/src/index.ts
> +import '@rijkshuisstijl-community/components-css/index.scss';
Nice!

2024-08-16 11:18 UTC, Rerbun commented on packages/components-react/package.json
> +    "@rijkshuisstijl-community/web-components-react": "workspace:*"
Ja dit zorgt voor rare conflict resolutions (dit is waarom we een lint error hadden gisteren met een andere package)

2024-08-19 08:37 UTC, Rerbun commented on packages/components-react/src/Alert.tsx
> +  icon?: string;
Is icon niet altijd exact dezelfde value als type? Kan je niet gewoon type gebruiken voor allebei?

2024-08-19 08:41 UTC, Rerbun commented on packages/components-react/src/Alert.tsx
> +      <UAlert ref={ref} {...restProps} type={type} role="alert">
We gebruiken overal Utrecht[Elementnaam], misschien goed om dit gelijk te houden bij alles en niet af te korten naar 1 letter

2024-08-19 09:03 UTC, Rerbun requested changes

2024-08-19 09:18 UTC, Rerbun approved these changes

2024-08-19 09:20 UTC, merged