Component/unordered list
nl-design-system/rijkshuisstijl-community pull request #528
Opened 2024-08-12 12:36 UTC by MeesD94

Closes #467

2024-08-20 08:08 UTC, Rerbun requested changes

2024-08-20 08:08 UTC, Rerbun commented on packages/components-css/unordered-list/index.scss
> +  padding-inline-start: var(--utrecht-unordered-list-item-padding-inline-start);
Zoals ik het zie (in de deployment) blijft padding-inline-start 0, er is dus geen spacing tussen de bullets en de tekst

2024-08-22 12:56 UTC, Rerbun submitted a review, later dismissed

2024-08-23 07:04 UTC, veslav3 approved these changes

2024-08-23 07:04 UTC, merged