WIP: first version of file-input
nl-design-system/rijkshuisstijl-community pull request #733
Opened 2024-10-02 13:30 UTC by MeesD94

WIP.

closes #449

2024-10-09 12:10 UTC, veslav3 requested changes

2024-10-09 12:10 UTC, veslav3 commented on packages/components-react/src/FileInput.tsx
> +  onFilesChange?: (callbackFiles: File[]) => void; // eslint-disable-line no-unused-vars
Deze vind ik lastig qua naamgeving. Is het handig om dit dichtbij het inputElement te houden qua naamgeving? onValueChange?

2024-10-09 12:10 UTC, veslav3 commented on packages/components-react/src/FileInputItem.tsx
> +  const formatBytes = (bytes: number): string => {
naamgeving; formatBytesToHigherOrderUnit

2024-10-09 12:10 UTC, veslav3 commented on packages/storybook/src/community/file-input.md
> +Met het `fileInput` component kunnen gebruikers meerdere bestanden uploaden.
de component in plaats van het component

2024-10-09 12:10 UTC, veslav3 commented on packages/storybook/src/community/file-input.stories.tsx
> +    maxFileSizeInBytes: 10_485_760,
Vanwaar de _?

2024-10-09 12:38 UTC, MeesD94 commented on packages/components-react/src/FileInput.test.tsx
> +describe('Form field with a textbox', () => {
klopt! goed gezien, heb een ander bestand gebruikt als voorbeeld. Ik pas het aan

2024-10-09 12:39 UTC, MeesD94 commented on packages/components-react/src/FileInput.tsx
> +  onFilesChange?: (callbackFiles: File[]) => void; // eslint-disable-line no-unused-vars
Goed idee!

2024-10-09 12:42 UTC, MeesD94 commented on packages/storybook/src/community/file-input.stories.tsx
> +    maxFileSizeInBytes: 10_485_760,
Leesbaarheid, ik vind 10_485_760 makkelijker lezen dan 10485760. Je kan dan snel zien dat het om een getal gaat van in de 10 miljoen.

2024-10-14 14:06 UTC, veslav3 approved these changes

2024-10-29 12:51 UTC, veslav3 approved these changes

2024-10-29 13:24 UTC, merged