feat(card): created first version without using tokens
nl-design-system/rijkshuisstijl-community pull request #734
Opened 2024-10-02 14:03 UTC by Rerbun

2024-10-09 07:10 UTC, AdhamAH submitted a review, later dismissed

2024-10-11 08:06 UTC, Rozerinay commented
**Design review**

Zou je bij de Default Card alle properties aan kunnen zetten (dus: description, metadata en link) zoals in Figma is uitgewerkt? De footer (waarin de Link zit) is nu bijv. ook leeg in de code.

<img width="352" alt="image" src="https://github.com/user-attachments/assets/6498c7d6-2b2b-4e4d-8bc5-acac569be352">

<img width="311" alt="image" src="https://github.com/user-attachments/assets/adacb180-5beb-41d4-a99f-d603eb7491f1">

---

De row gap lijkt niet aan te staan.

<img width="347" alt="image" src="https://github.com/user-attachments/assets/bee79826-71fb-4380-9524-706d940b19d1">

---

Bij hover kleurt de achtergrond niet mee.

<img width="350" alt="image" src="https://github.com/user-attachments/assets/5caad79f-5197-40e7-b5a1-3157b2aea904">


---

De opacity van de full bleed variant is nog te licht. Deze overlay zit op de Image en onder de content.

---

Ik heb bij de full bleed variant in de HTML de Metadata voorzien van tekst en ik zie dat die een donkere kleur heeft, omdat het de token `--rhc-card-as-link-metadata-color` overneemt. Is het mogelijk om deze kleur alsnog de witte kleur mee te geven? Ik had hier de token `todo.card-as-link.full-bleed.color` voor aangemaakt. 

<img width="346" alt="image" src="https://github.com/user-attachments/assets/2eab5b6a-1386-440d-b588-fc7d53bd5235">

---

De focus-style klopt nog niet.

<img width="348" alt="image" src="https://github.com/user-attachments/assets/9b828d18-6207-4095-b03c-43a3ca10e873">

---

De Image van de Horizontal variant is nu nog te groot. Ik heb in Figma de ratio 1:1 gebruikt (van 96px hoog). 

<img width="352" alt="image" src="https://github.com/user-attachments/assets/ef298fae-f9af-4db5-95b9-05546ac7f154">

2024-11-01 10:41 UTC, veslav3 commented
Cards moeten toegevoegd worden aan de templates:
<img width="888" alt="image" src="https://github.com/user-attachments/assets/427e92ef-1780-43be-a831-2268b5f3a458">

2024-11-01 12:02 UTC, veslav3 requested changes
template changes see other comment

2024-11-06 10:50 UTC, veslav3 approved these changes

2024-11-06 10:50 UTC, merged