Feature/ Navigation List
nl-design-system/rijkshuisstijl-community pull request #740
Opened 2024-10-07 11:05 UTC by AdhamAH

#557

2024-10-09 11:44 UTC, MeesD94 commented
Ik zie dat op de hover staat een white space op de onderkant van alle navigation list items zit behalve de laatste. 
<img width="188" alt="Screenshot 2024-10-09 at 13 41 21" src="https://github.com/user-attachments/assets/b53b6e80-0212-411b-bfd8-a8fa66f1ba18">

2024-10-09 11:45 UTC, MeesD94 requested changes
Check bovenstaande comment

2024-10-14 11:45 UTC, AdhamAH commented
@Rozerinay @MeesD94 

Ik heb de focus fixed. Ook heb ik de juiste token gezetten

2024-10-14 13:46 UTC, MeesD94 approved these changes

2024-10-14 13:46 UTC, merged