Feature/toggletip
nl-design-system/rijkshuisstijl-community pull request #745
Opened 2024-10-08 09:55 UTC by Rerbun

Token changes:
- todo-toggletip-* tokens renamed to rhc-toggletip-*

2024-10-09 09:49 UTC, MeesD94 requested changes

2024-10-09 09:49 UTC, MeesD94 commented on packages/components-react/src/Toggletip.tsx
> +  icon?: RijkshuisstijlIconID | ReactNode;
Moet de icon niet altijd gewoon een 'i' zijn?

2024-10-09 11:21 UTC, Rerbun commented on packages/components-react/src/Toggletip.tsx
> +  icon?: RijkshuisstijlIconID | ReactNode;
De ongebruikte properties zijn weggehaald

2024-10-11 07:22 UTC, MeesD94 approved these changes

2024-10-11 07:22 UTC, merged