PreHeading component
nl-design-system/rijkshuisstijl-community pull request #866
Opened 2024-11-04 14:05 UTC by JoeriRoijenga

2024-11-06 12:25 UTC, veslav3 requested changes

2024-11-06 12:25 UTC, veslav3 commented on packages/components-css/pre-heading/index.scss
> +  --utrecht-pre-heading-color: var(--utrecht-heading-1-color, inherit);
Is een pre-heading gerelateerd aan heading-1?

2024-11-06 12:25 UTC, veslav3 commented on packages/storybook/src/community/pre-heading.md
> +<PreHeading
Moeten in de voorbeeldcode ook de children getoond worden?

2024-11-06 12:29 UTC, JoeriRoijenga commented on packages/components-react/src/PreHeading.tsx
> +      <div className={'rhc-heading-container'} {...restProps}>
Wat is hier precies mis mee dan?

2024-11-06 12:36 UTC, JoeriRoijenga commented on packages/components-css/pre-heading/index.scss
> +  --utrecht-pre-heading-color: var(--utrecht-heading-1-color, inherit);
Nee niet perse, maar ik kon niet echt achterhalen welke kleur hier valide was. In het voorbeeld van het template en de screenshot die door Mees bij was gevoegd kwam ik uit op de heading 1 kleur. Hoe zou jij dit anders aanpakken?

2024-11-06 14:06 UTC, veslav3 commented on packages/components-css/pre-heading/index.scss
> +  --utrecht-pre-heading-color: var(--utrecht-heading-1-color, inherit);
Ik twijfel een beetje, het is in de toekomst kijken of dit ooit fout zou kunnen gaan, ik denk dat de kans klein genoeg is om het zo te laten staan.

2024-11-06 14:07 UTC, veslav3 commented on packages/components-react/src/PreHeading.tsx
> +      <div className={'rhc-heading-container'} {...restProps}>
@JoeriRoijenga nu lijkt het alsof er een variabele gebruikt wordt, maar je gebruikt eigenlijk gewoon een hardcoded string. {} gebruik je alleen als je iets met variabelen wilt doen.

2024-11-07 21:48 UTC, veslav3 approved these changes

2024-11-07 21:50 UTC, merged