restructure-details-template
nl-design-system/rijkshuisstijl-community pull request #907
Opened 2024-11-13 09:51 UTC by Aref-Akminasi

[#519](https://github.com/nl-design-system/rijkshuisstijl-community/issues/519)

Kun je controleren of de feedback van Rozerin in #519 goed is verwerkt?

2024-11-13 12:44 UTC, MeesD94 commented on pnpm-lock.yaml
> +  apps/rhc-templates/dist/types: {}
pnpm-lock.yaml hoeft nu niet te worden gecommit. er is geen aanpassing gedaan in de packages.

2024-11-13 12:47 UTC, MeesD94 commented
Ziet er goed uit! volgens mij zijn alle punten die Rozerin had verholpen. Kijk wel even naar de Accessibility tests in Storybook en probeer de violations te verhelpen! :) 
![Screenshot 2024-11-13 at 13 45 57](https://github.com/user-attachments/assets/bafbab15-de3f-4b73-afda-53c363b47c63)

2024-11-13 12:49 UTC, MeesD94 requested changes
Zie comments hierboven

2024-11-15 13:41 UTC, MeesD94 commented on packages/components-react/src/NavBar.tsx
> +  id?: string;
Ik snap niet helemaal waarom deze optioneel is?

2024-11-15 13:45 UTC, MeesD94 requested changes
Kijk even naar mijn comments! Wel goed dat de accessibility violations weg zijn.

2024-11-15 13:48 UTC, MeesD94 commented on packages/components-react/src/Hero.tsx
> +  heading?: string;
Als je de heading en subHeading properties optional maakt, moet je misschien hier ook controleren of ze wel moeten worden gerenderd. Als iemand nu `heroMessage=true` heeft staan, maar geen heading en/of subheading meegeeft , worden de componenten gerenderd met niks erin, wat ook weer een accessibility issue geeft (Headings should not be empty).

2024-11-18 09:26 UTC, Aref-Akminasi commented on packages/components-react/src/NavBar.tsx
> +  id?: string;
Ik heb inderdaad de `id` aan de map meegegeven en nu wordt hij meegegeven aan de `LinkListLink` component. Geen `key` error in de console meer.

2024-11-18 09:27 UTC, Aref-Akminasi commented on packages/components-react/src/Hero.tsx
> +  heading?: string;
Ik heb het wel optioneel gemaakt, maar dat is inderdaad niet verstandig. Ik heb het teruggedraaid en verder geen wijzigingen aangebracht in `Hero`, maar de nodige props van `Hero` meegegeven waar hij wordt aangeroepen in de `Details` template.

2024-11-18 09:44 UTC, MeesD94 approved these changes

2024-11-18 09:46 UTC, merged