(WIP) Feat/code input
nl-design-system/rijkshuisstijl-community pull request #933
Opened 2024-11-27 14:25 UTC by MeesD94

#823

2024-11-28 13:12 UTC, Rubenoo requested changes
Ziet er goed uit, als je vragen heb over de comments hoor ik het graag!

2024-11-28 13:12 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +      <div className={'rhc-code-input-container'} data-testid={'code-input-container'} ref={ref}>
Eventuele restProps worden nu niet gespread over de parent, is dit iets wat we willen?

2024-11-28 13:12 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +        <div className={'rhc-code-input-group'}>
Is het hierbij mogelijk om de hele code te copy pasten?

2024-11-28 13:12 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +  numberOfDigits: number;
Word er nu gevalideert dat dit ook echt het maximale/minimale is? Valt dit binnen de scope van dit component?

2024-11-28 13:12 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +        <Textbox
Misschien wil je autocomplete ook ondersteunen? Zie https://dev.to/madsstoumann/using-a-single-input-for-one-time-code-352l, en https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#one-time-code

2024-11-28 13:12 UTC, Rubenoo commented on packages/storybook/src/community/code-input.stories.tsx
> +export const Invalid: Story = {
Naast invalid willen we misschien ook een succesvol state toevoegen?

2024-11-28 13:12 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +              type="text"
Op dit moment opent er op telefoon een toetsenbord met letters en cijfers. dit lijkt me niet wenselijk omdat er je alleen nummers wilt invoeren. Daarom stel ik voor om `iputMode="numeric"` en eventueel `pattern="[0-9]*"` toe te voegen om te zorgen dat er alleen een nummeriek toetsenbord wordt geopend

2024-12-04 10:08 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +  // eslint-disable-next-line no-unused-vars
Was omdat die opzettelijk unused was, opgelost door eslint aan te passen om _value wel toe te staan

2024-12-04 10:08 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +  numberOfDigits: number;
Er staat nergens aangegeven wat de min en max moet zijn.

2024-12-04 10:24 UTC, MeesD94 commented on packages/storybook/src/community/code-input.stories.tsx
> +export const Invalid: Story = {
De code inputs zijn onderwater TextInputs, bij beide zijn er in de design geen succesvol states aanwezig. Dit kan uiteraard als er vraag naar is later nog worden toegevoegd. Voor nu hou ik mij even aan het design

2024-12-04 10:25 UTC, MeesD94 commented on packages/storybook/src/community/code-input.stories.tsx
> +export const Invalid: Story = {
[codeInput](https://www.figma.com/design/Nv5EsCW9ioWBUSi9m9JqOa/Local---Rijkshuisstijl---Bibliotheek?node-id=4106-10529&node-type=canvas&t=IhKBpuvK1lIwMbHt-0) [textInput](https://www.figma.com/design/txFX5MGRf4O904dtIFcGTF/NLDS---Rijkshuisstijl---Bibliotheek?node-id=859-981&node-type=canvas&t=FL8EnLyhygnsjq5U-0)

2024-12-04 10:26 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +}
Private mode toegevoegd die de nummers veranderen in '*'

2024-12-04 10:28 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +      <div className={'rhc-code-input-container'} data-testid={'code-input-container'} ref={ref}>
inderdaad, toegevoegd

2024-12-04 10:29 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +        <div className={'rhc-code-input-group'}>
Ja!

2024-12-04 12:21 UTC, MeesD94 commented on packages/components-css/src/code-input/_mixin.scss
> +@mixin rhc-code-input--hidden {
done

2024-12-04 13:13 UTC, Rubenoo commented on packages/components-css/src/code-input/_mixin.scss
> +@mixin rhc-code-input--hidden {
Bestaat hier echt geen utility class al voor? Dat lijkt me sterk want er moeten ook andere elementen visually hidden zijn

2024-12-04 13:13 UTC, Rubenoo commented on .eslintrc.js.json
> +    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
Waarom is dit toegevoegd?

2024-12-04 13:21 UTC, MeesD94 commented on .eslintrc.js.json
> +    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
Zodat we voor props wel functies kunnen gebruiken met unused vars als daar een '_' voor staat, dan kan de eslint ignore weg van eerder.

``` typescript 
onChange?: (_value: string) => void;
````

2024-12-05 08:16 UTC, MeesD94 commented on .eslintrc.js.json
> +    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
Omdat het een function type is, het geeft alleen aan welke parameters hij verwacht en wat hij terug geef. Heb de void veranderd in een string

2024-12-05 09:03 UTC, Rubenoo commented on packages/components-react/src/CodeInput.tsx
> +              onChange={() => {}}
Kan je deze uitleggen?

2024-12-05 09:15 UTC, MeesD94 commented on packages/components-react/src/CodeInput.tsx
> +              onChange={() => {}}
Was nog iets wat weg kon inderdaad!

2024-12-10 08:35 UTC, Rubenoo approved these changes
LGMT

2024-12-10 09:13 UTC, merged