edited hero props
nl-design-system/rijkshuisstijl-community pull request #989
Opened 2024-12-09 10:28 UTC by Aref-Akminasi

[#925](https://github.com/nl-design-system/rijkshuisstijl-community/issues/925)

2024-12-09 10:59 UTC, veslav3 commented on packages/components-react/src/Hero.tsx
> +          'Hero component: "subHeading" is provided, but "heading" is missing. Both should be set or omitted.',
Both should be set or omitted.

Ik denk dat dit overbodig is. De regels zijn complexer dan alleen dit. Je kan bijvoorbeeld ook alleen heading hebben.

2024-12-09 10:59 UTC, veslav3 commented on packages/components-react/src/Hero.tsx
> +          'Hero component: "subHeading" is provided, but "heading" is missing. Both should be set or omitted.',
'Hero component: "subHeading" is provided, but "heading" is missing.' Is dan voldoende voor de foutmelding

2024-12-09 11:25 UTC, veslav3 commented
Ik weet dat dit out-of-scope is voor de taak, maar dit lijkt me wel handig om te benoemen:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/dc0cde37-bf0d-475f-a96d-13367a625642">

Hoe weet je als leek dat de "heroMessage" boolean verbonden is aan de Heading property?

Het lijkt me handig om deze property te veranderen naar headingMessageVisible.

2024-12-09 11:27 UTC, veslav3 commented
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/d656da11-37aa-4094-80ff-4d0f7cfb7245">
Hier wordt niks weergegeven, maar als alles leeg is:
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/f1293baa-94ab-4659-a8e9-17887e2fcd58">
En de hero message staat op true dan verwacht ik ook een lege component met foutmelding.

2024-12-12 09:24 UTC, veslav3 commented on packages/storybook/src/community/hero.md
> +  imageAlt="Tullip field"
tulip field zal ik aanpassen

2024-12-12 09:26 UTC, veslav3 approved these changes
LGTM

2024-12-12 09:40 UTC, Rubenoo requested changes
Voor de rest ziet het er goed uit!

2024-12-12 09:40 UTC, Rubenoo commented on packages/components-react/src/Hero.tsx
> -      heroMessage,
Als de heroMessage hier verwijderd is, kan hij dan ook uit de interface?

2024-12-12 09:40 UTC, Rubenoo commented on packages/components-react/src/Hero.tsx
> +
Ik weet niet of dit de gewenste manier is. nu word pas op runtime gecheckt of de header en subheader goed zijn mee gegeven. Wellicht wil je dit in compile time checken?

2024-12-12 09:40 UTC, Rubenoo commented on packages/storybook/src/community/hero.md
> +import { Paragraph } from './Paragraph';
Waarom moet je deze importeren, je hoeft toch alleen de `Hero` te importeren?

2024-12-12 09:40 UTC, Rubenoo commented on packages/components-react/src/Hero.tsx
>        <div
is dit het semenatische element hiervoor?

2024-12-12 09:40 UTC, Rubenoo commented on packages/components-react/src/Hero.test.tsx
> +  it('logs an error and does not render when subHeading is provided without heading', () => {
Zie andere comment, als compile time gechecht word hier er waarschijnlijk geen test meer voor geschreven te worden

2024-12-12 09:42 UTC, Aref-Akminasi commented on packages/storybook/src/community/hero.md
> +import { Paragraph } from './Paragraph';
Klopt, ik heb het weg gehaald

2024-12-12 11:20 UTC, Aref-Akminasi commented on packages/components-react/src/Hero.tsx
> -      heroMessage,
heroMessage prop bestaat niet meer en er wordt naar heading gekeken

2024-12-12 11:21 UTC, Aref-Akminasi commented on packages/components-react/src/Hero.test.tsx
> +  it('logs an error and does not render when subHeading is provided without heading', () => {
Nu wordt het gedaan met TS interfaces, Unit test is weg gehaald

2024-12-12 14:14 UTC, Rubenoo submitted a review, later dismissed

2024-12-12 14:25 UTC, Aref-Akminasi commented on packages/components-react/src/Hero.tsx
>        <div
Ik heb het op Slack gevraagd, ik wacht nog op een antwoord

2024-12-13 12:08 UTC, Rubenoo approved these changes
LGTM

2024-12-13 12:08 UTC, merged